### ISSUE TITLE
Flaky test in investment test_views?

### ISSUE THREAD

**Issue by marcofucci** [uktrade/data-hub-leeloo#1237] opened 2018-11-20 14:24 UTC
test_document_delete_creates_user_event_log[permissions0-False-True] - datahub.investment.evidence.test.test_views.TestEvidenceDocumentViews

More info:
https://circleci.com/gh/uktrade/data-hub-leeloo/6182

**Comment by reupen** [comment] 2019-04-01 14:53
This seems to be a duplicate of #1153 which was fixed by #1345.

**Closed by reupen** 2019-04-01 14:53 UTC
